//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseSearchAndReg
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingTimes
    {
        public int Id { get; set; }
        public int SectionId { get; set; }
        public Days Day { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public Nullable<int> ClassroomId { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Classroom Classroom { get; set; }
    }
}
